### ISSUE TITLE
Latest Mono.Cecil fails agains Windows PDB from CoreFX

### ISSUE THREAD

**Issue by pjanotti** [jbevain/cecil#522]
Actually I am not sure if this is a Mono.Cecil or Roslyn issue but I'm starting here...

When doing code coverage runs on CoreFx repo the portable PDBs are replaced with anative PDBs stored on the WindowsPDB folder. The PDB is correctly identified as native, but latest Mono.Cecil expects MajorVersion and MinorVersion from CodeView header to be zero:

https://github.com/jbevain/cecil/blob/7bcab0af5965859f9b30d2cce318ea711ac40949/symbols/pdb/Mono.Cecil.Pdb/NativePdbReader.cs#L64-L65

However, the PDB has the values indicating that it is a embedded portable one, per tests in Roslyn repo:

https://github.com/dotnet/roslyn/blob/944ae114140ba77cbd4be370bf13a7f758f740b3/src/Compilers/CSharp/Test/Emit/PDB/PortablePdbTests.cs#L197-L199

The Cecil version currently used by OpenCover in CoreFx repo does not check for major and minor version.

Related:
https://github.com/OpenCover/opencover/pull/814
https://github.com/dotnet/corefx/issues/23588

**Comment by pjanotti** [comment]
Per conversation w/ @tmat:

> The debug directory entry indicates what PDB the binary was built with. That is not necessary the same PDB that is available when debugging though. The PDB can be converted to another format, usually Portable PDBs are converted to Windows PDBs. The tool (Mono.Cecil in this case) should accept either.

**Comment by jbevain** [comment]
Let' s have a look. The version check does look suspicious, and we should be able to validate on the Guid only. @pjanotti could you provide a dll and a pdb that trigger the mismatch?

**Comment by pjanotti** [comment]
Here you go @jbevain 
[System.Collections.zip](https://github.com/jbevain/cecil/files/2069404/System.Collections.zip)

**Comment by jbevain** [comment]
Fixed in ce905f79caa1f3a1661e2e25d9166af3ddda6fcd.

@tmat that being said, I'm seeing something weird in the debug symbols for:

`T[] System.Collections.Generic.EnumerableHelpers::ToArray(System.Collections.Generic.IEnumerable`1<T>,System.Int32&)`

In a scope I'm seeing 1 constant with a value `4`, likely this dude:

https://github.com/dotnet/corefx/blob/d7396b2b3dd78ff0152097c1ec7b2e43efcff9ce/src/Common/src/System/Collections/Generic/EnumerableHelpers.cs#L44

But the metadata token for the type points to the row zero of the Signature table.

**Comment by pjanotti** [comment]
Thanks @jbevain!

**Comment by brutaldev** [comment]
This issue still seems to be around. Using the `System.Collections` from @pjanotti trying to write a file throws a `ArgumentNullException`

Using code like this:

```
var readParams = new ReaderParameters() { AssemblyResolver = new DefaultAssemblyResolver(), ReadSymbols = true };
using (var ad = AssemblyDefinition.ReadAssembly(assemblyPath, readParams))
{
  ad.Write(outputAssemblyPath, new WriterParameters() { WriteSymbols = true });
}
```

Results in the following exception:
```
System.ArgumentNullException: Value cannot be null.
   at Mono.Cecil.SignatureWriter.WriteTypeSignature(TypeReference type)
   at Mono.Cecil.MetadataBuilder.GetConstantTypeSignature(TypeReference constant_type)
   at Mono.Cecil.Pdb.NativePdbWriter.DefineConstant(ConstantDebugInformation constant)
   at Mono.Cecil.Pdb.NativePdbWriter.DefineScope(ScopeDebugInformation scope, MethodDebugInformation info, MetadataToken& import_parent)
   at Mono.Cecil.Pdb.NativePdbWriter.DefineScope(ScopeDebugInformation scope, MethodDebugInformation info, MetadataToken& import_parent)
   at Mono.Cecil.Pdb.NativePdbWriter.DefineScope(ScopeDebugInformation scope, MethodDebugInformation info, MetadataToken& import_parent)
   at Mono.Cecil.Pdb.NativePdbWriter.DefineScope(ScopeDebugInformation scope, MethodDebugInformation info, MetadataToken& import_parent)
   at Mono.Cecil.Pdb.NativePdbWriter.Write(MethodDebugInformation info)
   at Mono.Cecil.Cil.CodeWriter.WriteUnresolvedMethodBody(MethodDefinition method)
   at Mono.Cecil.Cil.CodeWriter.WriteMethodBody(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
```
